In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from scipy.stats import boxcox
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as rmse
from sklearn.metrics import mean_absolute_error as mae
pd.options.display.max_rows = 50
from sklearn.preprocessing import QuantileTransformer

In [55]:
pd.options.display.max_rows = 200

# Data cleaning

#### Loading data

In [56]:
def load_data():
    global_terrorism_df= pd.read_csv("data/globalterrorismdb_0718dist.csv", encoding="ISO-8859-1", low_memory=False)
    return global_terrorism_df
#encoding="ISO-8859-1", low_memory=False

In [57]:
global_terrorism_df= load_data()

In [58]:
global_terrorism_df

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,NaN,0,NaN,182,Somalia,11,...,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...","""Highlights: Somalia Daily Media Highlights 1 ...",START Primary Collection,0,0,0,0,NaN
181687,201712310029,2017,12,31,NaN,0,NaN,200,Syria,10,...,NaN,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...","""Two Russian servicemen killed in Syria mortar...",START Primary Collection,-9,-9,1,1,NaN
181688,201712310030,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
181689,201712310031,2017,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181690,201712310032,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",NaN,START Primary Collection,-9,-9,0,-9,NaN

#### Removing duplicates

In [59]:
global_terrorism_df.shape

(181691, 135)

In [60]:
global_terrorism_df.drop_duplicates()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,NaN,0,NaN,182,Somalia,11,...,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...","""Highlights: Somalia Daily Media Highlights 1 ...",START Primary Collection,0,0,0,0,NaN
181687,201712310029,2017,12,31,NaN,0,NaN,200,Syria,10,...,NaN,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...","""Two Russian servicemen killed in Syria mortar...",START Primary Collection,-9,-9,1,1,NaN
181688,201712310030,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
181689,201712310031,2017,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
181690,201712310032,2017,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",NaN,START Primary Collection,-9,-9,0,-9,NaN

#### Dropping columns with more null values

In [61]:
nulls_df = pd.DataFrame(round(global_terrorism_df.isna().sum()/len(global_terrorism_df),4)*100)
nulls_df = nulls_df.reset_index()
nulls_df.columns = ['header_name', 'percent_nulls']
nulls_df

            header_name  percent_nulls
0               eventid           0.00
1                 iyear           0.00
2                imonth           0.00
3                  iday           0.00
4            approxdate          94.91
5              extended           0.00
6            resolution          98.78
7               country           0.00
8           country_txt           0.00
9                region           0.00
10           region_txt           0.00
11            provstate           0.23
12                 city           0.24
13             latitude           2.51
14            longitude           2.51
15          specificity           0.00
16             vicinity           0.00
17             location          69.46
18              summary          36.40
19                crit1           0.00
20                crit2           0.00
21                crit3           0.00
22            doubtterr           0.00
23          alternative          84.03
24      alternative_txt          84.03
25             multiple           0.00
26              success           0.00
27              suicide           0.00
28          attacktype1           0.00
29      attacktype1_txt           0.00
30          attacktype2          96.52
31      attacktype2_txt          96.52
32          attacktype3          99.76
33      attacktype3_txt          99.76
34            targtype1           0.00
35        targtype1_txt           0.00
36         targsubtype1           5.71
37     targsubtype1_txt           5.71
38                corp1          23.42
39              target1           0.35
40              natlty1           0.86
41          natlty1_txt           0.86
42            targtype2          93.87
43        targtype2_txt          93.87
44         targsubtype2          94.12
45     targsubtype2_txt          94.12
46                corp2          94.43
47              target2          93.93
48              natlty2          94.04
49          natlty2_txt          94.04
50            targtype3          99.35
51        targtype3_txt          99.35
52         targsubtype3          99.40
53     targsubtype3_txt          99.40
54                corp3          99.44
55              target3          99.35
56              natlty3          99.37
57          natlty3_txt          99.37
58                gname           0.00
59             gsubname          96.76
60               gname2          98.89
61            gsubname2          99.91
62               gname3          99.82
63            gsubname3          99.99
64               motive          72.17
65          guncertain1           0.21
66          guncertain2          98.92
67          guncertain3          99.82
68           individual           0.00
69               nperps          39.14
70             nperpcap          38.25
71              claimed          36.39
72            claimmode          89.50
73        claimmode_txt          89.50
74               claim2          98.96
75           claimmode2          99.66
76       claimmode2_txt          99.66
77               claim3          99.82
78           claimmode3          99.93
79       claimmode3_txt          99.93
80            compclaim          97.34
81            weaptype1           0.00
82        weaptype1_txt           0.00
83         weapsubtype1          11.43
84     weapsubtype1_txt          11.43
85            weaptype2          92.78
86        weaptype2_txt          92.78
87         weapsubtype2          93.65
88     weapsubtype2_txt          93.65
89            weaptype3          98.97
90        weaptype3_txt          98.97
91         weapsubtype3          99.07
92     weapsubtype3_txt          99.07
93            weaptype4          99.96
94        weaptype4_txt          99.96
95         weapsubtype4          99.96
96     weapsubtype4_txt          99.96
97           weapdetail          37.24
98                nkill           5.68
99              nkillus          35.47
100            nkillter          36.85
101              nwound           8.98
102            nwoundus          35.61
103            nwoundte          38.06
104            property           0.00
105          propextent          64.74
106      propextent_txt          64.74
107           propvalue          78.54
108         propcomment          68.10
109           ishostkid           0.10
110            nhostkid          92.53
111          nhostkidus          92.56
112              nhours          97.76
113               ndays          95.53
114              divert          99.82
115       kidhijcountry          98.18
116              ransom          57.41
117           ransomamt          99.26
118         ransomamtus          99.69
119          ransompaid          99.57
120        ransompaidus          99.70
121          ransomnote          99.72
122      hostkidoutcome          93.95
123  hostkidoutcome_txt          93.95
124           nreleased          94.28
125            addnotes          84.43
126              scite1          36.43
127              scite2          57.66
128              scite3          76.05
129            dbsource           0.00
130             INT_LOG           0.00
131            INT_IDEO           0.00
132            INT_MISC           0.00
133             INT_ANY           0.00
134             related          86.22

In [62]:
columns_drop = nulls_df[nulls_df['percent_nulls']>70]['header_name']  # dummy case with 70 
print(columns_drop.values)

['approxdate' 'resolution' 'alternative' 'alternative_txt' 'attacktype2'
 'attacktype2_txt' 'attacktype3' 'attacktype3_txt' 'targtype2'
 'targtype2_txt' 'targsubtype2' 'targsubtype2_txt' 'corp2' 'target2'
 'natlty2' 'natlty2_txt' 'targtype3' 'targtype3_txt' 'targsubtype3'
 'targsubtype3_txt' 'corp3' 'target3' 'natlty3' 'natlty3_txt' 'gsubname'
 'gname2' 'gsubname2' 'gname3' 'gsubname3' 'motive' 'guncertain2'
 'guncertain3' 'claimmode' 'claimmode_txt' 'claim2' 'claimmode2'
 'claimmode2_txt' 'claim3' 'claimmode3' 'claimmode3_txt' 'compclaim'
 'weaptype2' 'weaptype2_txt' 'weapsubtype2' 'weapsubtype2_txt' 'weaptype3'
 'weaptype3_txt' 'weapsubtype3' 'weapsubtype3_txt' 'weaptype4'
 'weaptype4_txt' 'weapsubtype4' 'weapsubtype4_txt' 'propvalue' 'nhostkid'
 'nhostkidus' 'nhours' 'ndays' 'divert' 'kidhijcountry' 'ransomamt'
 'ransomamtus' 'ransompaid' 'ransompaidus' 'ransomnote' 'hostkidoutcome'
 'hostkidoutcome_txt' 'nreleased' 'addnotes' 'scite3' 'related']

In [63]:
def drop_columns(global_terrorism_df):
    global_terrorism_df.drop(columns=['approxdate', 'resolution', 'attacktype2', 'attacktype2_txt', 'attacktype3',
                                      'attacktype3_txt', 'targtype2', 'targtype2_txt', 'targsubtype2',
                                      'targsubtype2_txt', 'corp2', 'target2', 'natlty2', 'natlty2_txt', 'targtype3',
                                      'targtype3_txt', 'targsubtype3', 'targsubtype3_txt', 'corp3', 'target3',
                                      'natlty3', 'natlty3_txt', 'gsubname', 'gname2', 'gsubname2', 'gname3',
                                      'gsubname3', 'guncertain2', 'guncertain3', 'claim2', 'claimmode2',
                                      'claimmode2_txt', 'claim3', 'claimmode3', 'claimmode3_txt', 'compclaim',
                                      'weaptype2', 'weaptype2_txt', 'weapsubtype2', 'weapsubtype2_txt', 'weaptype3',
                                      'weaptype3_txt', 'weapsubtype3', 'weapsubtype3_txt', 'weaptype4',
                                      'weaptype4_txt', 'weapsubtype4', 'weapsubtype4_txt', 'nhostkid', 'nhostkidus',
                                      'nhours', 'ndays', 'divert', 'kidhijcountry', 'ransomamt', 'ransomamtus',
                                      'ransompaid', 'ransompaidus', 'ransomnote', 'hostkidoutcome',
                                      'hostkidoutcome_txt', 'nreleased', 'alternative', 'alternative_txt', 
                                      'claimmode', 'claimmode_txt', 'addnotes', 'related', 'motive', 'propvalue', 
                                      'scite3'], inplace=True)
    return global_terrorism_df

In [64]:
global_terrorism_df=drop_columns(global_terrorism_df)

In [65]:
global_terrorism_df

,eventid,iyear,imonth,iday,extended,country,country_txt,region,region_txt,provstate,...,propcomment,ishostkid,ransom,scite1,scite2,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,197000000001,1970,7,2,0,58,Dominican Republic,2,Central America & Caribbean,NaN,...,NaN,0.0,0.0,NaN,NaN,PGIS,0,0,0,0
1,197000000002,1970,0,0,0,130,Mexico,1,North America,Federal,...,NaN,1.0,1.0,NaN,NaN,PGIS,0,1,1,1
2,197001000001,1970,1,0,0,160,Philippines,5,Southeast Asia,Tarlac,...,NaN,0.0,0.0,NaN,NaN,PGIS,-9,-9,1,1
3,197001000002,1970,1,0,0,78,Greece,8,Western Europe,Attica,...,NaN,0.0,0.0,NaN,NaN,PGIS,-9,-9,1,1
4,197001000003,1970,1,0,0,101,Japan,4,East Asia,Fukouka,...,NaN,0.0,0.0,NaN,NaN,PGIS,-9,-9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,0,182,Somalia,11,Sub-Saharan Africa,Middle Shebelle,...,NaN,0.0,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...",START Primary Collection,0,0,0,0
181687,201712310029,2017,12,31,0,200,Syria,10,Middle East & North Africa,Lattakia,...,Seven military planes were damaged in this att...,0.0,NaN,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...",START Primary Collection,-9,-9,1,1
181688,201712310030,2017,12,31,0,160,Philippines,5,Southeast Asia,Maguindanao,...,Houses were damaged in this attack.,0.0,NaN,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,START Primary Collection,0,0,0,0
181689,201712310031,2017,12,31,0,92,India,6,South Asia,Manipur,...,NaN,0.0,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,START Primary Collection,-9,-9,0,-9
181690,201712310032,2017,12,31,0,160,Philippines,5,Southeast Asia,Maguindanao,...,NaN,0.0,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",START Primary Collection,-9,-9,0,-9

In [66]:
def drop_columns(global_terrorism_df):
    global_terrorism_df.drop(columns=['approxdate', 
                                     
                                     
                                     
                                     
                                     
                                     
                                     ], inplace=True)
    return global_terrorism_df

#### Numerical Variables

In [67]:
numerical_columns= global_terrorism_df._get_numeric_data()
numerical_columns

,eventid,iyear,imonth,iday,extended,country,region,latitude,longitude,specificity,...,nwoundus,nwoundte,property,propextent,ishostkid,ransom,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,197000000001,1970,7,2,0,58,2,18.456792,-69.951164,1.0,...,NaN,NaN,0,NaN,0.0,0.0,0,0,0,0
1,197000000002,1970,0,0,0,130,1,19.371887,-99.086624,1.0,...,NaN,NaN,0,NaN,1.0,1.0,0,1,1,1
2,197001000001,1970,1,0,0,160,5,15.478598,120.599741,4.0,...,NaN,NaN,0,NaN,0.0,0.0,-9,-9,1,1
3,197001000002,1970,1,0,0,78,8,37.997490,23.762728,1.0,...,NaN,NaN,1,NaN,0.0,0.0,-9,-9,1,1
4,197001000003,1970,1,0,0,101,4,33.580412,130.396361,1.0,...,NaN,NaN,1,NaN,0.0,0.0,-9,-9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,0,182,11,2.359673,45.385034,2.0,...,0.0,0.0,-9,NaN,0.0,NaN,0,0,0,0
181687,201712310029,2017,12,31,0,200,10,35.407278,35.942679,1.0,...,0.0,0.0,1,4.0,0.0,NaN,-9,-9,1,1
181688,201712310030,2017,12,31,0,160,5,6.900742,124.437908,2.0,...,0.0,0.0,1,4.0,0.0,NaN,0,0,0,0
181689,201712310031,2017,12,31,0,92,6,24.798346,93.940430,1.0,...,0.0,0.0,-9,NaN,0.0,NaN,-9,-9,0,-9
181690,201712310032,2017,12,31,0,160,5,7.209594,124.241966,1.0,...,0.0,0.0,0,NaN,0.0,NaN,-9,-9,0,-9

#### Correcting numerical data types

In [68]:
numerical_columns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 43 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   eventid       181691 non-null  int64
 1   iyear         181691 non-null  int64
 2   imonth        181691 non-null  int64
 3   iday          181691 non-null  int64
 4   extended      181691 non-null  int64
 5   country       181691 non-null  int64
 6   region        181691 non-null  int64
 7   latitude      177135 non-null  float64
 8   longitude     177134 non-null  float64
 9   specificity   181685 non-null  float64
 10  vicinity      181691 non-null  int64
 11  crit1         181691 non-null  int64
 12  crit2         181691 non-null  int64
 13  crit3         181691 non-null  int64
 14  doubtterr     181690 non-null  float64
 15  multiple      181690 non-null  float64
 16  success       181691 non-null  int64
 17  suicide       181691 non-null  int64
 18  attacktype1   181691 non-null  int64
 19  targtype1     181691 non-null  int64
 20  targsubtype1  171318 non-null  float64
 21  natlty1       180132 non-null  float64
 22  guncertain1   181311 non-null  float64
 23  individual    181691 non-null  int64
 24  nperps        110576 non-null  float64
 25  nperpcap      112202 non-null  float64
 26  claimed       115571 non-null  float64
 27  weaptype1     181691 non-null  int64
 28  weapsubtype1  160923 non-null  float64
 29  nkill         171378 non-null  float64
 30  nkillus       117245 non-null  float64
 31  nkillter      114733 non-null  float64
 32  nwound        165380 non-null  float64
 33  nwoundus      116989 non-null  float64
 34  nwoundte      112548 non-null  float64
 35  property      181691 non-null  int64
 36  propextent    64065 non-null   float64
 37  ishostkid     181513 non-null  float64
 38  ransom        77381 non-null   float64
 39  INT_LOG       181691 non-null  int64
 40  INT_IDEO      181691 non-null  int64
 41  INT_MISC      181691 non-null  int64
 42  INT_ANY       181691 non-null  int64
dtypes: float64(21), int64(22)
memory usage: 59.6 MB

#### Categorical Variables

In [69]:
categorical_columns= global_terrorism_df.select_dtypes("object")
categorical_columns

,country_txt,region_txt,provstate,city,location,summary,attacktype1_txt,targtype1_txt,targsubtype1_txt,corp1,...,natlty1_txt,gname,weaptype1_txt,weapsubtype1_txt,weapdetail,propextent_txt,propcomment,scite1,scite2,dbsource
0,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,NaN,NaN,Assassination,Private Citizens & Property,Named Civilian,NaN,...,Dominican Republic,MANO-D,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,PGIS
1,Mexico,North America,Federal,Mexico city,NaN,NaN,Hostage Taking (Kidnapping),Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,...,Belgium,23rd of September Communist League,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,PGIS
2,Philippines,Southeast Asia,Tarlac,Unknown,NaN,NaN,Assassination,Journalists & Media,Radio Journalist/Staff/Facility,Voice of America,...,United States,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,PGIS
3,Greece,Western Europe,Attica,Athens,NaN,NaN,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,NaN,...,United States,Unknown,Explosives,Unknown Explosive Type,Explosive,NaN,NaN,NaN,NaN,PGIS
4,Japan,East Asia,Fukouka,Fukouka,NaN,NaN,Facility/Infrastructure Attack,Government (Diplomatic),Embassy/Consulate,NaN,...,United States,Unknown,Incendiary,NaN,Incendiary,NaN,NaN,NaN,NaN,PGIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,Somalia,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,The incident occurred near the town of Balcad.,12/31/2017: Assailants opened fire on a Somali...,Armed Assault,Military,Military Checkpoint,Somali National Army (SNA),...,Somalia,Al-Shabaab,Firearms,Unknown Gun Type,NaN,NaN,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...",START Primary Collection
181687,Syria,Middle East & North Africa,Lattakia,Jableh,The incident occurred at the Humaymim Airport.,12/31/2017: Assailants launched mortars at the...,Bombing/Explosion,Military,Military Barracks/Base/Headquarters/Checkpost,Russian Air Force,...,Russia,Muslim extremists,Explosives,"Projectile (rockets, mortars, RPGs, etc.)",Mortars were used in the attack.,Unknown,Seven military planes were damaged in this att...,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...",START Primary Collection
181688,Philippines,Southeast Asia,Maguindanao,Kubentog,The incident occurred in the Datu Hoffer distr...,12/31/2017: Assailants set fire to houses in K...,Facility/Infrastructure Attack,Private Citizens & Property,House/Apartment/Residence,Not Applicable,...,Philippines,Bangsamoro Islamic Freedom Movement (BIFM),Incendiary,Arson/Fire,NaN,Unknown,Houses were damaged in this attack.,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,START Primary Collection
181689,India,South Asia,Manipur,Imphal,The incident occurred in the Mantripukhri neig...,12/31/2017: Assailants threw a grenade at a Fo...,Bombing/Explosion,Government (General),Government Building/Facility/Office,Forest Department Manipur,...,India,Unknown,Explosives,Grenade,A thrown grenade was used in the attack.,NaN,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,START Primary Collection
181690,Philippines,Southeast Asia,Maguindanao,Cotabato City,NaN,12/31/2017: An explosive device was discovered...,Bombing/Explosion,Unknown,NaN,Unknown,...,Philippines,Unknown,Explosives,Unknown Explosive Type,An explosive device containing a detonating co...,NaN,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",START Primary Collection

#### Correcting categorical data types

In [70]:
categorical_columns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   country_txt       181691 non-null  object
 1   region_txt        181691 non-null  object
 2   provstate         181270 non-null  object
 3   city              181257 non-null  object
 4   location          55495 non-null   object
 5   summary           115562 non-null  object
 6   attacktype1_txt   181691 non-null  object
 7   targtype1_txt     181691 non-null  object
 8   targsubtype1_txt  171318 non-null  object
 9   corp1             139141 non-null  object
 10  target1           181055 non-null  object
 11  natlty1_txt       180132 non-null  object
 12  gname             181691 non-null  object
 13  weaptype1_txt     181691 non-null  object
 14  weapsubtype1_txt  160923 non-null  object
 15  weapdetail        114021 non-null  object
 16  propextent_txt    64065 non-null   object
 17  propcomment       57959 non-null   object
 18  scite1            115500 non-null  object
 19  scite2            76933 non-null   object
 20  dbsource          181691 non-null  object
dtypes: object(21)
memory usage: 29.1+ MB

In [71]:
categorical_columns

,country_txt,region_txt,provstate,city,location,summary,attacktype1_txt,targtype1_txt,targsubtype1_txt,corp1,...,natlty1_txt,gname,weaptype1_txt,weapsubtype1_txt,weapdetail,propextent_txt,propcomment,scite1,scite2,dbsource
0,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,NaN,NaN,Assassination,Private Citizens & Property,Named Civilian,NaN,...,Dominican Republic,MANO-D,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,PGIS
1,Mexico,North America,Federal,Mexico city,NaN,NaN,Hostage Taking (Kidnapping),Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",Belgian Ambassador Daughter,...,Belgium,23rd of September Communist League,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,PGIS
2,Philippines,Southeast Asia,Tarlac,Unknown,NaN,NaN,Assassination,Journalists & Media,Radio Journalist/Staff/Facility,Voice of America,...,United States,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,PGIS
3,Greece,Western Europe,Attica,Athens,NaN,NaN,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,NaN,...,United States,Unknown,Explosives,Unknown Explosive Type,Explosive,NaN,NaN,NaN,NaN,PGIS
4,Japan,East Asia,Fukouka,Fukouka,NaN,NaN,Facility/Infrastructure Attack,Government (Diplomatic),Embassy/Consulate,NaN,...,United States,Unknown,Incendiary,NaN,Incendiary,NaN,NaN,NaN,NaN,PGIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,Somalia,Sub-Saharan Africa,Middle Shebelle,Ceelka Geelow,The incident occurred near the town of Balcad.,12/31/2017: Assailants opened fire on a Somali...,Armed Assault,Military,Military Checkpoint,Somali National Army (SNA),...,Somalia,Al-Shabaab,Firearms,Unknown Gun Type,NaN,NaN,NaN,"""Somalia: Al-Shabaab Militants Attack Army Che...","""Highlights: Somalia Daily Media Highlights 2 ...",START Primary Collection
181687,Syria,Middle East & North Africa,Lattakia,Jableh,The incident occurred at the Humaymim Airport.,12/31/2017: Assailants launched mortars at the...,Bombing/Explosion,Military,Military Barracks/Base/Headquarters/Checkpost,Russian Air Force,...,Russia,Muslim extremists,Explosives,"Projectile (rockets, mortars, RPGs, etc.)",Mortars were used in the attack.,Unknown,Seven military planes were damaged in this att...,"""Putin's 'victory' in Syria has turned into a ...","""Two Russian soldiers killed at Hmeymim base i...",START Primary Collection
181688,Philippines,Southeast Asia,Maguindanao,Kubentog,The incident occurred in the Datu Hoffer distr...,12/31/2017: Assailants set fire to houses in K...,Facility/Infrastructure Attack,Private Citizens & Property,House/Apartment/Residence,Not Applicable,...,Philippines,Bangsamoro Islamic Freedom Movement (BIFM),Incendiary,Arson/Fire,NaN,Unknown,Houses were damaged in this attack.,"""Maguindanao clashes trap tribe members,"" Phil...",NaN,START Primary Collection
181689,India,South Asia,Manipur,Imphal,The incident occurred in the Mantripukhri neig...,12/31/2017: Assailants threw a grenade at a Fo...,Bombing/Explosion,Government (General),Government Building/Facility/Office,Forest Department Manipur,...,India,Unknown,Explosives,Grenade,A thrown grenade was used in the attack.,NaN,NaN,"""Trader escapes grenade attack in Imphal,"" Bus...",NaN,START Primary Collection
181690,Philippines,Southeast Asia,Maguindanao,Cotabato City,NaN,12/31/2017: An explosive device was discovered...,Bombing/Explosion,Unknown,NaN,Unknown,...,Philippines,Unknown,Explosives,Unknown Explosive Type,An explosive device containing a detonating co...,NaN,NaN,"""Security tightened in Cotabato following IED ...","""Security tightened in Cotabato City,"" Manila ...",START Primary Collection

#### Cleaning column country_txt

In [72]:
global_terrorism_df["country_txt"].unique().tolist()

['Dominican Republic',
 'Mexico',
 'Philippines',
 'Greece',
 'Japan',
 'United States',
 'Uruguay',
 'Italy',
 'East Germany (GDR)',
 'Ethiopia',
 'Guatemala',
 'Venezuela',
 'West Germany (FRG)',
 'Switzerland',
 'Jordan',
 'Spain',
 'Brazil',
 'Egypt',
 'Argentina',
 'Lebanon',
 'Ireland',
 'Turkey',
 'Paraguay',
 'Iran',
 'United Kingdom',
 'Colombia',
 'Bolivia',
 'Nicaragua',
 'Netherlands',
 'Belgium',
 'Canada',
 'Australia',
 'Pakistan',
 'Zambia',
 'Sweden',
 'Costa Rica',
 'South Yemen',
 'Cambodia',
 'Israel',
 'Poland',
 'Taiwan',
 'Panama',
 'Kuwait',
 'West Bank and Gaza Strip',
 'Austria',
 'Czechoslovakia',
 'India',
 'France',
 'South Vietnam',
 'Brunei',
 'Zaire',
 "People's Republic of the Congo",
 'Portugal',
 'Algeria',
 'El Salvador',
 'Thailand',
 'Haiti',
 'Sudan',
 'Morocco',
 'Cyprus',
 'Myanmar',
 'Afghanistan',
 'Peru',
 'Chile',
 'Honduras',
 'Yugoslavia',
 'Ecuador',
 'New Zealand',
 'Malaysia',
 'Singapore',
 'Botswana',
 'Jamaica',
 'Chad',
 'North Yemen',
 'Andorra',
 'Syria',
 'South Korea',
 'United Arab Emirates',
 'South Africa',
 'Kenya',
 'Iraq',
 'Somalia',
 'Tanzania',
 'Sri Lanka',
 'Namibia',
 'Bahamas',
 'Nigeria',
 'Barbados',
 'Trinidad and Tobago',
 'Bangladesh',
 'Angola',
 'Mauritania',
 'Saudi Arabia',
 'Djibouti',
 'Indonesia',
 'Malta',
 'Rhodesia',
 'Soviet Union',
 'Denmark',
 'Western Sahara',
 'Guyana',
 'Mozambique',
 'Tunisia',
 'Uganda',
 'Norway',
 'Lesotho',
 'Gabon',
 'Libya',
 'Bahrain',
 'Hong Kong',
 'Senegal',
 'Zimbabwe',
 'Guinea',
 'Grenada',
 'New Hebrides',
 'Belize',
 'Guadeloupe',
 'Martinique',
 'Vatican City',
 'Albania',
 'Central African Republic',
 'Seychelles',
 'Dominica',
 'Qatar',
 'Bulgaria',
 'Suriname',
 'Swaziland',
 'Luxembourg',
 'Iceland',
 'French Guiana',
 'Falkland Islands',
 'Burkina Faso',
 'New Caledonia',
 'Romania',
 'Niger',
 'Nepal',
 'Togo',
 'Finland',
 'Fiji',
 'Ghana',
 'Maldives',
 'Mauritius',
 'Hungary',
 'Laos',
 'Papua New Guinea',
 'China',
 'Liberia',
 'Republic of the Congo',
 'Mali',
 'Germany',
 'Yemen',
 'Rwanda',
 'Sierra Leone',
 'Cameroon',
 'Cuba',
 'Croatia',
 'Georgia',
 'Azerbaijan',
 'Madagascar',
 'Lithuania',
 'Burundi',
 'Ukraine',
 'Moldova',
 'Armenia',
 'Russia',
 'Ivory Coast',
 'Kazakhstan',
 'Antigua and Barbuda',
 'Bosnia-Herzegovina',
 'Equatorial Guinea',
 'Tajikistan',
 'Malawi',
 'Uzbekistan',
 'Latvia',
 'Estonia',
 'Vietnam',
 'Comoros',
 'Benin',
 'Slovak Republic',
 'Macedonia',
 'Wallis and Futuna',
 'Belarus',
 'Czech Republic',
 'Slovenia',
 'Gambia',
 'North Korea',
 'Eritrea',
 'St. Kitts and Nevis',
 'French Polynesia',
 'Macau',
 'Kyrgyzstan',
 'Vanuatu',
 'Democratic Republic of the Congo',
 'Kosovo',
 'Solomon Islands',
 'East Timor',
 'St. Lucia',
 'Guinea-Bissau',
 'Montenegro',
 'International',
 'Turkmenistan',
 'Serbia-Montenegro',
 'Bhutan',
 'Serbia',
 'South Sudan']

#### Cleaning column region_txt

In [73]:
global_terrorism_df["region_txt"].unique().tolist()

['Central America & Caribbean',
 'North America',
 'Southeast Asia',
 'Western Europe',
 'East Asia',
 'South America',
 'Eastern Europe',
 'Sub-Saharan Africa',
 'Middle East & North Africa',
 'Australasia & Oceania',
 'South Asia',
 'Central Asia']

In [75]:
global_terrorism_df.to_csv("global_terrorism_df_cleaned.csv",index=False)